Repository 9oormthon-univ/2025_SEASONTHON_TEAM_73_FE, pull requests merged in 2025-09, with the labels that each got.

#23 [Feature] : 필터 기능 구현 완료
  app/(tabs)/(home)/filter.tsx
  app/(tabs)/(home)/index.tsx
  app/(tabs)/(home)/region.tsx
  app/login.tsx
  shared/api/request.ts
  shared/components/Skeleton/Skeleton.tsx
  shared/components/index.ts
  shared/constants/gender.ts
  shared/constants/index.ts
  shared/types/response.ts
  widgets/home/api/fetchPostList.ts
  widgets/home/api/index.ts
  widgets/home/api/submitPostSearch.ts
  widgets/home/components/RoomListItem.tsx
  widgets/home/components/RoomSearchFilter.tsx
  widgets/home/constants/filter.ts
  widgets/home/constants/index.ts
  widgets/home/constants/regions.ts
  widgets/home/contexts/filterDefault.tsx
  widgets/home/contexts/filterRegion.ts
  widgets/home/types/filter.ts
  widgets/home/types/index.ts
  widgets/home/types/room.ts
  widgets/region/SelectedAreasSection.tsx
Labels: Feature

#27 [Design] : 탭바 디자인 변경 및 오류 핸들링 UI 추가
  app/(tabs)/(chat)/index.tsx
  app/(tabs)/(home)/index.tsx
  app/(tabs)/(home)/region.tsx
  app/(tabs)/_layout.tsx
  app/(tabs)/chat/_layout.tsx
  app/(tabs)/chat/index.tsx
  app/(tabs)/chat/room/[roomId].tsx
  app/(tabs)/chat/room/_layout.tsx
  package-lock.json
  package.json
  widgets/chat/ChatRequestList.tsx
  widgets/chat/ChatRoomList.tsx
  widgets/menu/components/Logo.tsx
  widgets/menu/components/Tab.tsx
  widgets/menu/components/TabsHandler.tsx
  widgets/menu/components/TabsUi.tsx
  widgets/menu/constants/index.ts
  widgets/menu/index.ts
  widgets/menu/theme/index.tsx
Labels: Design

#65 [Fix] 2단계 인증 로직 수정
  app/(tabs)/(home)/detail/[postId].tsx
  widgets/detail/ProfileSection.tsx
Labels: Feature, Refactor
